version: '3'

services:
  webapi:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: asp-web 
    ports:
      - "80:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
